### ISSUE TITLE
Configuration is too cumbersome

### ISSUE THREAD

**Issue by askfiy** [windwp/windline.nvim#36]
Sorry, I haven't tried lua language before.

Although the built-in wlsample.airline is nicely styled, I would like to modify it a bit, like adding gps and github status.

But I don't know where to start, I'm sure I've read the readme file countless times. .

**Comment by windwp** [comment]
i still prefer you copy a wlsample and modify it.

there is another way.
https://github.com/windwp/windline.nvim/wiki/component#add-or-remove-component

**Comment by nyngwang** [comment]
@windwp: Based on the requirement of OP do you mind write one for us?

**Comment by windwp** [comment]
No i don't have intent to do that
 i create many theme because it fun and it proves that windline is flexible.

there are many statusline with easy config you can use lualine or something else. if you want something special you can use windline.

if you want both you need to write something that belong to you :)
